### ISSUE TITLE
Publish java-spiffe-helper to Maven Central

### ISSUE THREAD

**Issue by erikgb** [spiffe/java-spiffe#37]
I was struggeling yesterday to configure a CI pipeline to build java-spiffe-helper from source. Are there any reasons why this artifact is not built and published to Maven Central from this repository? Seems like "the missing piece of the puzzle": https://search.maven.org/search?q=g:io.spiffe

**Comment by maxlambrecht** [comment]
Hi @erikgb, it's not in the maven central repo because it was not thought to be used as maven or gradle dependency but as a standalone jar, and the jar was published on Github: https://github.com/spiffe/java-spiffe/releases, built for Linux (https://github.com/spiffe/java-spiffe/releases/download/v0.6.2/java-spiffe-helper-0.6.2-linux-x86_64.jar)  and for MacOS (https://github.com/spiffe/java-spiffe/releases/download/v0.6.2/java-spiffe-helper-0.6.2-osx-x86_64.jar).

**Comment by erikgb** [comment]
@maxlambrecht Thanks, that makes sense. I wasn't aware of the release artifacts. Closing issue.

**Comment by evan2645** [comment]
Should we document something to this effect in the readme?

**Comment by maxlambrecht** [comment]
I'll add it to the README, thanks @evan2645
